//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamsWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DreamsWorksEntities : DbContext
    {
        private static DreamsWorksEntities _context;
        public DreamsWorksEntities()
            : base("name=DreamsWorksEntities")
        {
        }

        public static DreamsWorksEntities GetContext()
        {
            if (_context == null)
                _context = new DreamsWorksEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }



        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<Animator> Animators { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Types_Events> Types_Events { get; set; }
    }
}
