//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamsWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Id_Holiday { get; set; }
        public int Id_Animator { get; set; }
        public System.DateTime Date_Holiday { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public Nullable<int> Garland { get; set; }
        public Nullable<int> Firework { get; set; }
        public Nullable<int> Petard { get; set; }
        public string Event { get; set; }
        public decimal PriceGarland { get; set; }
        public decimal PriceFirework { get; set; }
        public decimal PricePetard { get; set; }
        public int Service_animator { get; set; }
    
        public virtual Animator Animator { get; set; }
    }
}
