//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamsWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types_Events
    {
        public int Id { get; set; }
        public string Event { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
